## Copyright (c) 2021 Intel Corporation
#
## SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: iometrics
spec:
        #runtimeClassName: runc
  runtimeClassName: kata
  containers:
  - name: iometrics
    image: ubuntu:latest
    env:
      - name: http_proxy
        value: http://child-prc.intel.com:913
      - name: https_proxy
        value: http://child-prc.intel.com:913
      
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep infinity" ]

